# Single source for UI strings: regenerates src/Kakitome.App/Strings/{en-US,ja-JP}/Resources.resw.
# Usage: python tools/strings.py
import os
from xml.sax.saxutils import escape

STRINGS = [
    # key, en-US, ja-JP
    ("AppDisplayName", "Kakitome", "Kakitome"),
    ("Recording_Header.Text", "Record", "録音"),
    ("Recording_Microphone.Header", "Microphone", "マイク"),
    ("Recording_SystemAudio.Header", "Also record system audio", "システム音声も録音する"),
    ("Recording_OutputDevice.Header", "Output device to record", "録音する出力デバイス"),
    ('Recording_AudioSource.Header', 'System audio to record', '録音するシステム音声'),
    ('Recording_AllPcAudio', 'All PC audio', 'PC のすべての音声'),
    ("Recording_Project.Header", "Project", "プロジェクト"),
    ("Recording_Project.PlaceholderText", "Choose a project", "プロジェクトを選択"),
    ("Recording_Title.Header", "Title (optional)", "タイトル（任意）"),
    ("Recording_Start.Content", "Start recording", "録音開始"),
    ("Recording_Stop.Content", "Stop and save", "停止して保存"),
    ("Recording_Cancel.Content", "Discard", "破棄"),
    ("Recording_Elapsed.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "Recorded time", "録音時間"),
    ("Recording_Pause", "Pause", "一時停止"),
    ("Recording_Resume", "Resume", "再開"),
    ("Recording_DefaultDevice", "Windows default ({0})", "Windows の既定 ({0})"),
    ("Recording_DefaultDeviceNone", "Windows default", "Windows の既定"),
    ("State_Idle", "Ready to record", "録音できます"),
    ("State_Recording", "Recording", "録音中"),
    ("State_Paused", "Paused", "一時停止中"),
    ("State_Suspended", "Paused while the PC sleeps", "PC のスリープ中は一時停止しています"),
    ("State_Stopping", "Saving…", "保存しています…"),
    ("State_Stopped", "Saved", "保存しました"),
    ("State_Cancelled", "Discarded", "破棄しました"),
    ("Stream_Active", "Capturing", "取り込み中"),
    ("Stream_Reconnecting", "Device disconnected — waiting for it to come back (recording continues)", "デバイスが切断されました。再接続を待っています（録音は継続中）"),
    ("Stream_Stopped", "Stopped", "停止"),
    ("Stream_Failed", "Could not write audio", "音声を書き込めませんでした"),
    ("Kind_Microphone", "Microphone", "マイク"),
    ("Kind_SystemAudio", "System audio", "システム音声"),
    ("Kind_Application", "App audio", "アプリの音声"),
    ("CancelDialog_Title", "Discard this recording?", "この録音を破棄しますか？"),
    ("CancelDialog_Content", "The recording will be moved to the Recycle Bin. You can restore it from there.", "録音はごみ箱に移動されます。ごみ箱から元に戻せます。"),
    ("CancelDialog_Primary", "Discard", "破棄"),
    ("CancelDialog_Close", "Keep recording", "録音を続ける"),
    ("Error_InsufficientDisk", "There is not enough free disk space to record safely. Free up space and try again.", "安全に録音するためのディスク空き容量が足りません。空き容量を増やしてから、もう一度お試しください。"),
    ("Error_DeviceUnavailable", "The selected audio device is not available. Check the connection or choose another device.", "選択した音声デバイスを使用できません。接続を確認するか、別のデバイスを選んでください。"),
    ("Error_NoSources", "Choose at least one audio source.", "音声ソースを 1 つ以上選んでください。"),
    ("Error_StartFailed", "Recording could not be started. Please try again.", "録音を開始できませんでした。もう一度お試しください。"),
    ("Error_StopFailed", "The recording could not be finalized. The audio is kept and will be repaired the next time Kakitome starts.", "録音を正常に終了できませんでした。音声は保持されており、次回の起動時に修復されます。"),
    ("Error_AlreadyRecording", "A recording is already in progress.", "すでに録音中です。"),
    ("Info_Saved", "Saved to {0}", "保存先: {0}"),
    ("Info_StoppedUnexpectedly", "Recording stopped unexpectedly (for example, the disk is almost full). The audio recorded so far has been saved.", "録音が予期せず停止しました（ディスク容量不足など）。それまでの音声は保存されています。"),
    ("Info_HotkeyUnavailable", "The shortcut {0} is already used by another app. You can change it in Settings.", "ショートカット {0} は他のアプリで使用されています。設定で変更できます。"),
    ("Tray_Start", "Start recording", "録音開始"),
    ("Tray_Stop", "Stop and save", "停止して保存"),
    ("Tray_Open", "Open Kakitome", "Kakitome を開く"),
    ("Tray_Exit", "Exit", "終了"),
    ("Tray_Tooltip_Idle", "Kakitome", "Kakitome"),
    ("Tray_Tooltip_Recording", "Kakitome — recording", "Kakitome — 録音中"),
    # --- Navigation shell ---
    ("Nav_Home.Content", "Home", "ホーム"),
    ("Nav_Library.Content", "Library", "ライブラリ"),
    ("Nav_Projects.Content", "Projects", "プロジェクト"),
    ("Nav_Queue.Content", "Processing", "処理キュー"),
    ("Nav_Search.Content", "Search", "検索"),
    # --- Home ---
    ("Home_Recent.Text", "Recent recordings", "最近の録音"),
    ("Home_NoRecordings.Text", "No recordings yet. Start a recording or import audio or video files.", "まだ録音はありません。録音を開始するか、音声・動画ファイルを取り込んでください。"),
    ("Home_NeedsModel.Title", "Install a speech recognition model", "音声認識モデルをインストールしてください"),
    ("Home_NeedsModelText", "Transcripts are created on this PC. Download a model once to enable transcription.", "文字起こしはこの PC 上で行います。最初に一度だけモデルをダウンロードしてください。"),
    ("Home_ModelDownloading", "Downloading the recommended model for this PC ({0}). Transcription starts once it is ready; progress is shown in the processing queue.", "この PC に推奨のモデル（{0}）をダウンロードしています。完了すると文字起こしできるようになります。進行状況は処理キューで確認できます。"),
    ("Home_OpenModels.Content", "Open model settings", "モデルの設定を開く"),
    ("Home_Processing.Text", "Processing", "処理状況"),
    ("Home_OpenQueue.Content", "Open processing queue", "処理キューを開く"),
    ("Home_DropHint.Text", "You can also drop audio or video files onto this window to import them.", "音声・動画ファイルをこのウィンドウにドロップしても取り込めます。"),
    ("Import_Button.Content", "Import files…", "ファイルを取り込む…"),
    ("Info_Importing", "Importing {0} file(s) into the project \"{1}\"…", "{0} 件のファイルをプロジェクト「{1}」に取り込んでいます…"),
    ("ImportUrl_Button.Content", "Import from URL…", "URL から取り込む…"),
    ("ImportUrl_Title", "Import from a URL", "URL から取り込む"),
    ("ImportUrl_Placeholder", "https://…", "https://…"),
    ("ImportUrl_Help", "Kakitome downloads the audio with yt-dlp and transcribes it on this PC. Only import media you are allowed to download.", "yt-dlp で音声をダウンロードし、この PC 上で文字起こしします。ダウンロードが許可されているメディアだけを取り込んでください。"),
    ("ImportUrl_Start", "Import", "取り込む"),
    ("ImportUrl_Invalid", "Enter an http:// or https:// address.", "http:// または https:// で始まるアドレスを入力してください。"),
    ("ImportUrl_NeedsTool", "URL import needs yt-dlp. Install it (or choose your own yt-dlp.exe) in Settings > Import.", "URL からの取り込みには yt-dlp が必要です。[設定] > [取り込み] でインストールするか、yt-dlp.exe を選んでください。"),
    ("Info_ImportingUrl", "Downloading from {0} into the project \"{1}\"…", "{0} からプロジェクト「{1}」にダウンロードしています…"),
    ("Error_ImportUnsupported", "{0} is not a supported file type.", "{0} は対応していないファイル形式です。"),
    # --- Library ---
    ("Library_Header.Text", "Library", "ライブラリ"),
    ("Library_Filter.PlaceholderText", "Filter by title, project or tag", "タイトル・プロジェクト・タグで絞り込み"),
    ("Library_Empty.Text", "No recordings match.", "該当する録音はありません。"),
    ("Library_ShowAll.Content", "Show all projects", "すべてのプロジェクトを表示"),
    ("Library_Open.Text", "Open", "開く"),
    ("Library_OpenFolder.Text", "Show in File Explorer", "エクスプローラーで表示"),
    ("Library_Delete.Text", "Move to Recycle Bin…", "ごみ箱に移動…"),
    ("Status_Recording", "Recording", "録音中"),
    ("Status_Processing", "Processing: {0}", "処理中: {0}"),
    ("Status_Failed", "{0} failed", "{0}に失敗"),
    ("Status_ExternalChanges", "Edited outside Kakitome", "Kakitome の外で編集されています"),
    ("Status_Ready", "Transcript and summary ready", "文字起こし・要約済み"),
    ("Status_Transcribed", "Transcribed", "文字起こし済み"),
    ("Status_NotTranscribed", "Not transcribed", "未文字起こし"),
    ("Stage_audio_analyze", "Audio analysis", "音声の解析"),
    ("Stage_asr", "Transcription", "文字起こし"),
    ("Stage_cleanup", "Cleanup", "整形"),
    ("Stage_summary", "Summary", "要約"),
    ("Stage_index", "Search index", "検索用の索引"),
    ("Stage_model_install", "Model download", "モデルのダウンロード"),
    ("Stage_import_file", "Import", "取り込み"),
    ("Stage_import_url", "Download", "ダウンロード"),
    ("Notify_Ready", "Transcript and summary are ready", "文字起こしと要約ができました"),
    ("Notify_ReadyMany", "{0} recordings have been processed.", "{0} 件の録音の処理が完了しました。"),
    ("Notify_Failed", "Processing failed", "処理に失敗しました"),
    ("Notify_FailedBody", "{0} — {1}", "{0} — {1}"),
    ("Notify_FailedMany", "{0} jobs failed. Open the processing queue for details.", "{0} 件の処理が失敗しました。詳しくは処理キューを開いてください。"),
    # --- Queue ---
    ("Queue_Header.Text", "Processing queue", "処理キュー"),
    ("Queue_Empty.Text", "Nothing has been processed in the last 7 days.", "直近 7 日間の処理はありません。"),
    ("Queue_AllDone", "All processing is complete.", "すべての処理が完了しています。"),
    ("Queue_ActiveCount", "{0} item(s) in progress or waiting.", "{0} 件を処理中または待機中です。"),
    ("Queue_Engine", "{0} · {1}", "{0} · {1}"),
    ("Locality_Local", "on this PC", "この PC で処理"),
    ("Queue_Cancel.Content", "Cancel", "キャンセル"),
    ("Queue_Retry.Content", "Retry", "再試行"),
    ("Queue_Pause.Content", "Pause", "一時停止"),
    ("Queue_Resume.Content", "Resume", "再開"),
    ("Queue_Open.Content", "Open recording", "録音を開く"),
    ("JobState_Pending", "Waiting", "待機中"),
    ("JobState_Running", "Running", "実行中"),
    ("JobState_Paused", "Paused", "一時停止中"),
    ("JobState_Succeeded", "Done", "完了"),
    ("JobState_Failed", "Failed", "失敗"),
    ("JobState_Cancelled", "Cancelled", "キャンセル済み"),
    ("Wait_None", "Starting soon", "まもなく開始"),
    ("Wait_Dependency", "Waiting for the previous step", "前の工程を待っています"),
    ("Wait_RetryBackoff", "Will retry shortly", "しばらくしてから再試行します"),
    ("Wait_OnBattery", "Waiting for AC power to save battery", "バッテリー節約のため電源接続を待っています"),
    ("Wait_EnergySaver", "Waiting while Windows Energy Saver is on", "Windows の省電力モードがオンのため待機しています"),
    ("Wait_LowBattery", "Waiting: battery is low. Processing continues on AC power.", "バッテリー残量が少ないため待機しています。電源につなぐと再開します。"),
    ("Wait_SystemBusy", "Waiting until the PC is less busy", "PC の負荷が下がるのを待っています"),
    ("Wait_LowMemory", "Waiting for free memory", "空きメモリが増えるのを待っています"),
    ("Wait_LowDiskSpace", "Paused: the disk is almost full", "ディスクの空きが少ないため停止しています"),
    ("Wait_RecordingInProgress", "Waiting until the recording ends", "録音が終わるのを待っています"),
    ("Wait_ConcurrencyLimit", "Waiting for another task to finish", "他の処理が終わるのを待っています"),
    # --- Search ---
    ("Search_Header.Text", "Search", "検索"),
    ("Search_Box.PlaceholderText", "Search titles, transcripts and summaries", "タイトル・文字起こし・要約を検索"),
    ("Search_NoResults", "No matches.", "一致する結果はありません。"),
    ("Search_ResultCount", "{0} recording(s), {1} match(es)", "{0} 件の録音・{1} 件の一致"),
    ("HitKind_Title", "Title", "タイトル"),
    ("HitKind_Transcript", "Transcript", "文字起こし"),
    ("HitKind_Summary", "Summary", "要約"),
    # --- Projects ---
    ("Projects_Header.Text", "Projects", "プロジェクト"),
    ("Projects_NewName.PlaceholderText", "New project name", "新しいプロジェクト名"),
    ("Projects_Create.Content", "Create project", "プロジェクトを作成"),
    ("Projects_NewName.Header", "New project", "新しいプロジェクト"),
    ("Projects_NameRequired", "Type a name for the new project first.", "先にプロジェクト名を入力してください。"),
    ("Projects_AlreadyExists", "A project named “{0}” already exists.", "「{0}」というプロジェクトは既にあります。"),
    ("Recording_NewProject.Content", "New…", "新規…"),
    ("Recording_NewProject.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name", "New project", "新しいプロジェクト"),
    ("NewProjectDialog_Title", "New project", "新しいプロジェクト"),
    ("NewProjectDialog_Placeholder", "Project name", "プロジェクト名"),
    ("NewProjectDialog_Primary", "Create", "作成"),
    ("Projects_CountAndLast", "{0} recording(s) · last {1}", "{0} 件 · 最終 {1}"),
    ("Projects_Empty", "No recordings yet", "録音はまだありません"),
    ("Info_ProjectCreated", "Created project “{0}”.", "プロジェクト「{0}」を作成しました。"),
    # --- Recording detail ---
    ("Detail_TabTranscript.Text", "Transcript", "文字起こし"),
    ("Detail_TabSummary.Text", "Summary", "要約"),
    ("Detail_NoTranscript.Text", "No transcript yet. It is created automatically after recording, or use Re-transcribe.", "まだ文字起こしはありません。録音後に自動で作成されます。「再文字起こし」でも作成できます。"),
    ("Detail_NoSummary.Text", "No summary yet.", "まだ要約はありません。"),
    ("Detail_NoAudio", "Audio is not available for this recording.", "この録音の音声はありません。"),
    ("Detail_AudioRemoved", "The audio was removed on {0} after processing, as set in Settings > Recording. The transcript and summary are kept.", "設定（録音の保存形式）に従い、処理完了後の {0} に音声を削除しました。文字起こしと要約は残っています。"),
    ("Detail_ReTranscribe.Label", "Re-transcribe", "再文字起こし"),
    ("Detail_RegenerateSummary.Label", "Regenerate summary", "要約を作り直す"),
    ("Detail_OpenFolder.Label", "Show in File Explorer", "エクスプローラーで表示"),
    ("Detail_TranscriptInfo", "{0} · {1}", "{0} · {1}"),
    ("Detail_Suggestions.Text", "Suggested edits", "修正の提案"),
    ("Detail_SuggestionText", "“{0}” → {1}", "「{0}」→ {1}"),
    ("Detail_Accept.Content", "Apply", "適用"),
    ("Detail_EditHint.Text", "Click the text to play from there. Double-click (or press F2) to correct the part being played. Corrections are kept when cleanup runs again.", "文章をクリックすると、その位置から再生します。ダブルクリック（または F2 キー）で、その部分を修正できます。修正内容は再整形しても保持されます。"),
    ("TranscriptKind_Raw", "Raw", "未整形"),
    ("TranscriptKind_Clean", "Cleaned", "整形済み"),
    ("TranscriptKind_Edited", "Edited", "編集済み"),
    ("Summary_KeyPoints", "Key points", "要点"),
    ("Summary_Decisions", "Decisions", "決定事項"),
    ("Summary_ActionItems", "Action items", "アクションアイテム"),
    ("Summary_Questions", "Open questions", "質問・未解決事項"),
    ("Summary_Topics", "Topics", "トピック"),
    ("Summary_Owner", "owner: {0}", "担当: {0}"),
    ("Summary_Due", "due: {0}", "期限: {0}"),
    # --- Dialogs / messages ---
    ("Dialog_Cancel", "Cancel", "キャンセル"),
    ("DeleteDialog_Title", "Move this recording to the Recycle Bin?", "この録音をごみ箱に移動しますか？"),
    ("DeleteDialog_Content", "“{0}” and its files (audio, transcript, summary) will be moved to the Recycle Bin. You can restore them from there.", "「{0}」とそのファイル（音声・文字起こし・要約）をごみ箱に移動します。ごみ箱から元に戻せます。"),
    ("DeleteDialog_Primary", "Move to Recycle Bin", "ごみ箱に移動"),
    ("Info_MovedToRecycleBin", "“{0}” was moved to the Recycle Bin.", "「{0}」をごみ箱に移動しました。"),
    ("Error_RecycleBinUnavailable", "This folder cannot be moved to the Recycle Bin, so nothing was deleted.", "このフォルダはごみ箱に移動できないため、何も削除していません。"),
    ("RetranscribeDialog_Title", "Transcribe again?", "文字起こしをやり直しますか？"),
    ("RetranscribeDialog_Content", "The current transcript will be replaced. A transcript.md you edited by hand is kept as a separate copy.", "現在の文字起こしを置き換えます。手で編集した transcript.md がある場合は別名で残します。"),
    ("RetranscribeDialog_Primary", "Transcribe again", "やり直す"),
    ("Info_Queued", "Added to the processing queue.", "処理キューに追加しました。"),
    ("Error_ExternalEditConflict", "The transcript files were edited outside Kakitome. Reload the recording before editing here.", "文字起こしのファイルが Kakitome の外で編集されています。再読み込みしてから編集してください。"),
    ("Error_RecordingMissing", "This recording is no longer in the Library.", "この録音はライブラリにありません。"),
    ("Error_RecordingUnreadable", "This recording could not be read: {0}", "この録音を読み込めませんでした：{0}"),
    # --- Settings ---
    ("Settings_Recording.Text", "Recording", "録音"),
    ('Settings_SystemAudio.Header', 'Also record system audio by default', '既定でシステム音声も録音する'),
    ("Settings_PreventSleep.Header", "Keep the PC awake while recording", "録音中は PC をスリープさせない"),
    ('Settings_KeepRecording.Header', 'Keep recording when the window is closed', 'ウィンドウを閉じても録音を続ける'),
    ('Settings_Hotkey.Header', 'Start/stop shortcut', '録音の開始/停止ショートカット'),
    ("Settings_Transcription.Text", "Transcription", "文字起こし"),
    ("Settings_Language.Header", "Spoken language", "話している言語"),
    ("Settings_AsrModel.Header", "Speech recognition model", "音声認識モデル"),
    ('Settings_Glossary.Text', 'Glossary', '用語辞書'),
    ('Settings_GlossaryHelp.Text', 'Terms and names in a glossary are given to speech recognition as hints, and its corrections are applied after transcription. Kakitome does not come with one: import a text file that you or an AI assistant wrote.', '用語辞書の専門用語や人名は文字起こしのヒントになり、「誤 -> 正」の修正は文字起こしの後に適用されます。辞書はアプリに含まれていません。ご自身や AI に作ってもらったテキストファイルを取り込んでください。'),
    ('Glossary_Scope.Header', 'Applies to', '適用先'),
    ('Glossary_ScopeAll', 'All recordings', 'すべての録音'),
    ('Glossary_ScopeProject', 'Project: {0}', 'プロジェクト: {0}'),
    ('Glossary_Status', '{0} terms, {1} corrections', '{0} 語・修正 {1} 件'),
    ('Glossary_None', 'No glossary', '辞書なし'),
    ('Glossary_Import.Content', 'Import .txt…', 'テキストを取り込む…'),
    ('Glossary_Edit.Content', 'Edit', '編集'),
    ('Glossary_Remove.Content', 'Stop using', '使わない'),
    ('Glossary_Imported', 'Imported {0} terms and {1} corrections.', '{0} 語と修正 {1} 件を取り込みました。'),
    ('Glossary_Skipped', '{0} line(s) were skipped (first: line {1}, "{2}").', '{0} 行を読み飛ばしました（最初は {1} 行目「{2}」）。'),
    ('Glossary_PreviousKept', 'The previous glossary was kept as {0}.', '以前の辞書は {0} として残しています。'),
    ('Glossary_ApplyHint', 'It is used for new transcriptions; to apply it to an existing recording, use Re-transcribe on that recording.', 'これからの文字起こしに使われます。既存の録音に使うには、録音の詳細で「再文字起こし」を実行してください。'),
    ('Glossary_Invalid_tooLarge', 'This file is too large for a glossary (512 KB at most).', '辞書としては大きすぎるファイルです（最大 512 KB）。'),
    ('Glossary_Invalid_notText', 'This is not a text file.', 'テキストファイルではありません。'),
    ('Glossary_Invalid_empty', 'No entries were found. Write one term per line.', '項目が見つかりませんでした。1 行に 1 項目ずつ書いてください。'),
    ('Glossary_Failed', 'Could not import the glossary: {0}', '辞書を取り込めませんでした：{0}'),
    ('Glossary_EditHint', 'Opened in your text editor. Save the file and it is used from the next transcription.', 'テキストエディターで開きました。保存すると次の文字起こしから使われます。'),
    ('Glossary_RemoveTitle', 'Stop using this glossary?', 'この辞書を使わないようにしますか？'),
    ('Glossary_RemoveContent', 'The file is not deleted. It is renamed to glossary.removed-<date>.txt in the same folder.', 'ファイルは削除しません。同じフォルダーに glossary.removed-<日時>.txt という名前で残します。'),
    ('Glossary_RemovePrimary', 'Stop using', '使わない'),
    ('Glossary_Removed', 'The glossary is no longer used. The file was kept as {0}.', '辞書を使わないようにしました。ファイルは {0} として残しています。'),
    ('Glossary_Copied', 'Copied. Paste it into your AI assistant, save the answer as a .txt file, then import it.', 'コピーしました。AI に貼り付けて、返ってきた内容を .txt で保存し、取り込んでください。'),
    ('Glossary_HowTo.Header', 'Format, and how to make one with AI', '書式と AI での作り方'),
    ('Glossary_AiHeader.Text', 'Request to give an AI assistant', 'AI への依頼文（例）'),
    ('Glossary_AiRequestBox.[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name', 'Request text', 'AI への依頼文'),
    ('Glossary_Copy.Content', 'Copy', 'コピー'),
    ('Glossary_Format', 'A glossary is a UTF-8 text file with one entry per line:\n• a term, name or proper noun, e.g. Kubernetes. These are given to speech recognition as hints. Put the most important ones first: about 20 are used at a time, and the rest take turns.\n• a correction "wrong -> right", e.g. cube cuddle -> kubectl. Applied to every transcript after recognition; the original wording stays in transcript.json.\n• lines starting with # are notes.\nThe shared glossary is Library\\Projects\\glossary.txt; a project\'s glossary is glossary.txt in that project\'s folder. Both are used for recordings in the project.', '用語辞書は UTF-8 のテキストファイルで、1 行に 1 項目を書きます。\n・専門用語・人名・固有名詞（例：罪刑法定主義）… 文字起こしのヒントになります。重要な語を上に書いてください。一度に使われるのは 20 語ほどで、残りは順番に使われます。\n・「誤 -> 正」の修正（例：新居の自由 -> 信教の自由）… 文字起こしの後に置き換えます。元の文は transcript.json に残ります。\n・# で始まる行はメモです。\n共通の辞書は Library\\Projects\\glossary.txt、プロジェクトの辞書はそのプロジェクトのフォルダーの glossary.txt です。プロジェクトの録音には両方が使われます。'),
    ('Glossary_AiRequest', 'Please write a glossary for transcribing audio about: [describe the subject, course or meeting here]\n\nFormat (plain text, one entry per line, no numbering or explanations):\n- Technical terms, people\'s names, product names, case names and other proper nouns from this field, most important first, at most about 200 lines.\n- If you know a likely mishearing, add a line "wrong -> right", e.g. cube cuddle -> kubectl.\n- Lines starting with # are comments.', '次の内容の音声を文字起こしするための用語辞書を作ってください。\n内容：［ここに分野・授業名・会議の内容などを書く］\n\n書式（プレーンテキスト、1 行に 1 項目、番号や説明は付けない）：\n- この分野でよく出る専門用語・人名・固有名詞・判例名・製品名などを、重要なものから順に、多くても 200 行程度\n- 音声認識が間違えそうな書き方がわかる場合は「誤 -> 正」の形で 1 行に書く（例：新居の自由 -> 信教の自由）\n- # で始まる行はコメント'),
    ('Detail_GlossaryTip.Title', 'A glossary can improve accuracy', '用語辞書で精度を上げられます'),
    ('GlossaryTip_Text', 'If technical terms or names were written as other words that sound the same, a glossary fixes them. 1) Copy the request and give it to an AI assistant together with transcript.txt from this recording\'s folder. 2) Save the answer as a .txt file and choose "Import glossary and transcribe again". The glossary is used for every recording in the project "{0}".', '専門用語や人名が同じ読みの別の語になっている場合は、用語辞書で直せます。① 依頼文をコピーし、この録音のフォルダーにある transcript.txt と一緒に AI アシスタントに渡します。② 返ってきた内容を .txt で保存し、「辞書を取り込んで再文字起こし」を選びます。辞書はプロジェクト「{0}」のすべての録音に使われます。'),
    ('Detail_GlossaryCopy.Content', 'Copy request for an AI', 'AI への依頼文をコピー'),
    ('Detail_GlossaryShowFile.Content', 'Show transcript.txt', 'transcript.txt の場所を開く'),
    ('Detail_GlossaryImport.Content', 'Import glossary and transcribe again…', '辞書を取り込んで再文字起こし…'),
    ('Detail_GlossaryHide.Content', "Don't show this tip again", '今後このおすすめを表示しない'),
    ('GlossaryTip_Topics', ' Topics: {0}.', '話題：{0}。'),
    ('GlossaryTip_TopicSeparator', ', ', '、'),
    ('GlossaryTip_Request', 'The attached transcript (transcript.txt) of "{0}" was made by speech recognition.{1}\nSome technical terms, names, case names or product names were written as other words that sound the same or similar.\nPlease write a glossary for this subject that I can also use for future recordings, in this format (plain text, one entry per line, no numbering or explanations):\n- Each misrecognition in the transcript as "wrong -> right". Copy "wrong" exactly as it appears in the transcript (at least 2 characters), e.g. cube cuddle -> kubectl.\n- Do not use an ordinary word that is correct elsewhere in the text as "wrong": it is replaced everywhere.\n- Leave out corrections you are not sure about.\n- Then the important technical terms, names and proper nouns of this field, most important first, at most about 200 lines.\n- Lines starting with # are comments.', '添付した文字起こし（transcript.txt）は、「{0}」を音声認識で文字にしたものです。{1}\n専門用語・人名・判例名・製品名などが、同じ読みや似た読みの別の語に誤変換されている箇所があります。\nこの分野の今後の録音にも使える用語辞書を、次の書式で作ってください（プレーンテキスト、1 行に 1 項目、番号や説明は付けない）。\n- 文字起こしの中の誤変換を「誤 -> 正」の形で書く。「誤」は文字起こしの表記をそのまま 2 文字以上で写す（例：新居の自由 -> 信教の自由）\n- ほかの箇所で正しく使われている普通の言葉は「誤」にしない（文字起こし全体で置き換わるため）\n- 確信が持てない修正は書かない\n- 続けて、この分野でよく出る専門用語・人名・固有名詞を、重要なものから順に、多くても 200 行程度\n- # で始まる行はコメント'),
    ('GlossaryTip_Copied', 'Copied. Paste it into the AI assistant you use and attach transcript.txt. Kakitome itself sends nothing.', 'コピーしました。お使いの AI アシスタントに貼り付け、transcript.txt を添付してください。Kakitome 自身は何も送信しません。'),
    ('GlossaryTip_Imported', 'Glossary of the project "{0}" imported: {1} terms, {2} corrections.', 'プロジェクト「{0}」の用語辞書を取り込みました（用語 {1}、修正 {2}）。'),
    ('GlossaryTip_Hidden', 'This tip will not be shown again. You can turn it back on in Settings › Transcription › Glossary.', 'このおすすめは今後表示しません。設定 › 文字起こし › 用語辞書 で元に戻せます。'),
    ('Notify_GlossaryTip', 'Tip: a glossary can fix misrecognized technical terms.', 'ヒント：用語辞書で専門用語の誤変換を直せます。'),
    ('Settings_GlossaryTips.Content', 'Suggest a glossary for longer recordings that have none', '用語辞書のない長めの録音で、辞書づくりをすすめる'),
    ("Settings_Mode.Header", "When to process", "処理するタイミング"),
    ("Settings_AutoProcess.Header", "Transcribe and summarize new recordings automatically", "新しい録音を自動で文字起こし・要約する"),
    ("Settings_Models.Text", "Models", "モデル"),
    ('Settings_ModelsHint.Text', 'Models run on this PC and are stored separately from your Library; they can be removed at any time. Models that use an NPU are not supported yet.', 'モデルはこの PC の中で動き、ライブラリとは別に保存されます。いつでも削除できます。NPU（AI 専用プロセッサー）を使うモデルには、まだ対応していません。'),
    ("Settings_Header.Text", "Settings", "設定"),
    ('Settings_YtDlp.Text', 'yt-dlp (needed to import from URLs)', 'yt-dlp（URL からの取り込みに必要）'),
    ("Settings_YtDlpHelp.Text", "Install the verified copy above, or choose a yt-dlp.exe you downloaded yourself. The installed copy is used when present.", "上のボタンで検証済みの yt-dlp をインストールするか、ご自身で入手した yt-dlp.exe を選んでください。インストール済みのものが優先されます。"),
    ("Settings_YtDlpBrowse.Content", "Choose yt-dlp.exe…", "yt-dlp.exe を選ぶ…"),
    ("Settings_YtDlpClear.Content", "Clear", "解除"),
    ("Settings_YtDlpNone", "Not set", "未設定"),
    ('Settings_Storage.Text', 'Storage', '保存場所と容量'),
    ("Settings_OpenLibrary.Content", "Open", "開く"),
    ('Settings_LibrarySize.Text', 'Library', 'ライブラリ'),
    ("Settings_ModelsSize.Text", "Models", "モデル"),
    ('Settings_Retention.Header', 'Keep recordings as', '録音の保存形式'),
    ('Retention_raw', 'Original quality (lossless WAV)', '元の品質（ロスレス WAV）'),
    ('Retention_m4a', 'M4A (AAC, smaller) after processing', '処理後に M4A（AAC・小さめ）へ変換'),
    ('Retention_mp3', 'MP3 (smaller) after processing', '処理後に MP3（小さめ）へ変換'),
    ('Retention_deleteAfterProcessing', 'Delete audio after processing (keep text only)', '処理後に音声を削除（テキストのみ残す）'),
    ('RetentionDeleteDialog_Title', 'Delete audio after processing?', '処理後に音声を削除しますか？'),
    ('RetentionDeleteDialog_Content', "From now on, a recording's audio is deleted once its transcript and summary have been created successfully. You will not be able to play it or transcribe it again. Each recording's metadata notes that its audio was removed.", '今後は、文字起こしと要約が正常に作成された録音の音声を削除します。削除後は再生や再文字起こしはできません。音声を削除したことは各録音の metadata.json に記録されます。'),
    ('RetentionDeleteDialog_Primary', 'Delete audio after processing', '処理後に音声を削除する'),
    ('Settings_LiveTranscript.Header', 'Show a live transcript while recording', '録音中にライブ文字起こしを表示する'),
    ('Live_Header.Text', 'Live transcript (preview)', 'ライブ文字起こし（プレビュー）'),
    ('Live_Starting', 'Loading {0}…', '{0} を読み込んでいます…'),
    ('Live_Running', '{0} on this PC. This is a preview; the final transcript is made after recording and may differ.', 'この PC の {0} で表示中。プレビューのため、録音後に作成される正式な文字起こしとは異なる場合があります。'),
    ('Live_NoModel', 'Install a speech recognition model in Settings > Models to see a live transcript.', 'ライブ文字起こしを表示するには、[設定] > [モデル] で音声認識モデルをインストールしてください。'),
    ('Live_PowerSaving', 'Live transcript is paused to save battery. The recording continues normally.', 'バッテリー節約のためライブ文字起こしを一時停止しています。録音は通常どおり続いています。'),
    ('Live_SourceMic', 'Mic', 'マイク'),
    ('Live_SourceOthers', 'PC audio', 'PC の音声'),
    ('Model_Verify.Content', 'Verify', '検証'),
    ('Model_Repair.Content', 'Repair', '修復'),
    ('Model_Verifying', 'Checking the files…', 'ファイルを確認しています…'),
    ('Model_Verified', 'Verified: the files match the published checksums.', '検証済み: ファイルは公開されているチェックサムと一致しています。'),
    ('Model_VerifyFailed', 'The files are damaged and will not be used. Choose Repair to download the damaged parts again.', 'ファイルが破損しているため使用しません。[修復] で破損部分を再ダウンロードしてください。'),
    ('Settings_Notices.Content', 'Third-party notices', 'サードパーティの通知'),
    ('Notices_Title', 'Third-party notices', 'サードパーティの通知'),
    ('Notices_Missing', 'The notices file was not found in this installation.', 'このインストールには通知ファイルが見つかりません。'),
    ('Dialog_Close', 'Close', '閉じる'),
    ('YtDlp_Install.Content', 'Install yt-dlp', 'yt-dlp をインストール'),
    ('YtDlp_Installed', '{0} is installed (verified).', '{0} をインストール済み（検証済み）。'),
    ('YtDlp_NotInstalled', 'Not installed.', 'インストールされていません。'),
    ('YtDlpDialog_Title', 'Download yt-dlp?', 'yt-dlp をダウンロードしますか？'),
    ('YtDlpDialog_Content', '{0} ({1}) will be downloaded from {2} and checked against its published SHA-256 before use. License: {3}. It is used only when you import from a URL.', '{0}（{1}）を {2} からダウンロードし、公開されている SHA-256 と照合してから使用します。ライセンス: {3}。URL からの取り込み時にだけ使用します。'),
    ('Settings_SummaryEngine.Header', 'Summaries', '要約の方法'),
    ('SummaryEngine_auto', 'Local AI when installed (better; uses more power), otherwise extraction', 'ローカル AI（インストール済みの場合。高精度・電力を多く使用）／なければ抜き出し'),
    ('SummaryEngine_extractive', 'Extraction only (fast, light)', '抜き出しのみ（高速・軽量）'),
    ('Settings_CacheSize.Text', 'Cache', 'キャッシュ'),
    ('Settings_AppDataSize.Text', 'App data (settings, index, logs)', 'アプリのデータ（設定・索引・ログ）'),
    ('Settings_BackupsSize.Text', 'Backups', 'バックアップ'),
    ('Settings_Backup.Text', 'Backup', 'バックアップ'),
    ('Settings_BackupHelp.Text', 'A backup is one .kakitome-backup file with all recordings, transcripts and summaries (models are not included; they can be downloaded again).', 'バックアップは、すべての録音・文字起こし・要約を含む 1 つの .kakitome-backup ファイルです（モデルは再ダウンロードできるため含みません）。'),
    ('Backup_Now.Content', 'Back up now', '今すぐバックアップ'),
    ('Backup_Restore.Content', 'Restore from backup…', 'バックアップから復元…'),
    ('Backup_OpenFolder.Content', 'Open backup folder', 'バックアップのフォルダを開く'),
    ('Settings_AutomaticBackup.Header', 'Back up automatically every week', '毎週自動でバックアップする'),
    ('Backup_Last', 'Last backup: {0}', '前回のバックアップ: {0}'),
    ('Backup_None', 'No backup yet.', 'バックアップはまだありません。'),
    ('Backup_Queued', 'The backup has started. Progress is shown in the processing queue.', 'バックアップを開始しました。進行状況は処理キューに表示されます。'),
    ('Restore_Title', 'Restore from this backup?', 'このバックアップから復元しますか？'),
    ('Restore_Content', 'Recordings in {0} that are not in your Library are restored. Recordings already in your Library are left exactly as they are.', '{0} に含まれる録音のうち、ライブラリにないものを復元します。ライブラリにある録音は一切変更しません。'),
    ('Restore_Primary', 'Restore', '復元する'),
    ('Restore_Queued', 'Restoring. Progress is shown in the processing queue.', '復元しています。進行状況は処理キューに表示されます。'),
    ('Stage_backup_create', 'Backup', 'バックアップ'),
    ('Stage_backup_restore', 'Restore', '復元'),
    ('Stage_audio_retain', 'Audio retention', '音声の保存形式'),
    ('Settings_Maintenance.Text', 'Maintenance', 'メンテナンス'),
    ('Maintenance_ClearCache.Content', 'Clear', '消去'),
    ('Maintenance_ClearCacheCard.Description', 'Deletes temporary files only. Recordings are not affected.', '一時ファイルだけを削除します。録音には影響しません。'),
    ('Maintenance_ResetConfig.Content', 'Reset', 'リセット'),
    ('Maintenance_ResetConfigCard.Description', 'Restores default settings. Recordings and models are kept.', '設定を既定値に戻します。録音とモデルはそのままです。'),
    ('Maintenance_FactoryReset.Content', 'Reset…', '初期化…'),
    ('Maintenance_FactoryResetCard.Description', 'Removes settings, index, processing history, models and cache, then restarts. Your Library is kept and re-indexed.', '設定・索引・処理履歴・モデル・キャッシュを削除して再起動します。ライブラリは残り、読み込み直されます。'),
    ('Maintenance_Uninstall.Content', 'Uninstall…', 'アンインストール…'),
    ('Maintenance_UninstallCard.Description', 'Choose what to keep, then continue in Windows Settings.', '残すデータを選んでから、Windows の設定でアンインストールします。'),
    ('Maintenance_CacheCleared', 'Cache cleared ({0} freed).', 'キャッシュを消去しました（{0} 解放）。'),
    ('Maintenance_ConfigReset', 'Settings were reset to their defaults.', '設定を既定値に戻しました。'),
    ('Maintenance_StopRecordingFirst', 'Stop the current recording first.', '先に録音を停止してください。'),
    ('Maintenance_UninstallProblems', 'Some data could not be removed: {0}. Close programs that use it and try again.', '一部のデータを削除できませんでした: {0}。使用中のプログラムを閉じてからやり直してください。'),
    ('ResetConfig_Title', 'Reset all settings?', 'すべての設定をリセットしますか？'),
    ('ResetConfig_Content', 'Settings return to their defaults. Recordings, transcripts, summaries and models are not changed.', '設定が既定値に戻ります。録音・文字起こし・要約・モデルは変更されません。'),
    ('ResetConfig_Primary', 'Reset', 'リセット'),
    ('FactoryReset_Title', 'Reset Kakitome to its initial state?', 'Kakitome を初期状態に戻しますか？'),
    ('FactoryReset_Content', 'Settings, the search index, processing history, downloaded models and cache are removed and Kakitome restarts. Your Library ({0}) is kept and indexed again; models can be downloaded again.', '設定・検索索引・処理履歴・ダウンロードしたモデル・キャッシュを削除し、Kakitome を再起動します。ライブラリ（{0}）は残り、再び読み込まれます。モデルは再ダウンロードできます。'),
    ('FactoryReset_Primary', 'Reset and restart', 'リセットして再起動'),
    ('Uninstall_Title', 'Uninstall Kakitome', 'Kakitome のアンインストール'),
    ('Uninstall_Intro', 'Your recordings are kept unless you choose otherwise. Selected items are moved to the Recycle Bin (models are deleted).', '選択しない限り録音は残ります。選択した項目はごみ箱へ移動します（モデルは削除されます）。'),
    ('Uninstall_RemoveLibrary', 'Also move my Library (recordings, transcripts, summaries — {0}) to the Recycle Bin', 'ライブラリ（録音・文字起こし・要約 — {0}）もごみ箱へ移動する'),
    ('Uninstall_RemoveModels', 'Remove downloaded models ({0})', 'ダウンロードしたモデルを削除する（{0}）'),
    ('Uninstall_ModelsWithApp', 'Downloaded models ({0}) are removed with the app (they can be downloaded again)', 'ダウンロードしたモデル（{0}）はアプリと一緒に削除されます（再ダウンロードできます）'),
    ('Uninstall_RemoveBackups', 'Also move backups ({0}) to the Recycle Bin', 'バックアップ（{0}）もごみ箱へ移動する'),
    ('Uninstall_AppState', 'Settings, index and cache ({0}) are removed with the app.', '設定・索引・キャッシュ（{0}）はアプリと一緒に削除されます。'),
    ('Uninstall_Primary', 'Continue to uninstall', 'アンインストールへ進む'),
    ('Settings_Appearance.Text', 'Appearance', '表示'),
    ("Settings_Theme.Header", "Theme", "テーマ"),
    ("Settings_UiLanguage.Header", "Display language", "表示言語"),
    ("Settings_RestartRequired.Message", "Restart Kakitome to apply the display language.", "表示言語は Kakitome の再起動後に反映されます。"),
    ("Settings_Notifications.Header", "Notify me when processing finishes or fails", "処理の完了・失敗を通知する"),
    ("Settings_About.Text", "About", "このアプリについて"),
    ("Settings_Releases.Content", "Releases on GitHub", "GitHub のリリースページ"),
    ("Settings_Privacy.Text", "Recordings, transcripts and summaries stay on this PC. Kakitome uses no cloud service. It contacts the internet only to download models and tools and, when turned on, to check GitHub for a newer version (only the version is asked for).", "録音・文字起こし・要約はこの PC の中だけで扱います。クラウドサービスは使用しません。インターネットに接続するのは、モデルやツールのダウンロードと、オンのときの新しいバージョンの確認（GitHub にバージョンを問い合わせるだけ）のみです。"),
    ("Mode_Auto", "Automatic (on battery: slower, pauses below 30 %)", "自動（バッテリー時は控えめに処理、残り 30% 未満で一時停止）"),
    ("Mode_AlwaysProcess", "Always (also on battery)", "常に処理（バッテリー時も）"),
    ("Mode_BatterySaver", "Battery first (only on AC with a charged battery)", "バッテリー優先（十分充電された電源接続時のみ）"),
    ("Language_Auto", "Detect automatically", "自動判定"),
    ("UiLanguage_System", "Same as Windows", "Windows と同じ"),
    ("Theme_System", "Same as Windows", "Windows と同じ"),
    ("Theme_Light", "Light", "ライト"),
    ("Theme_Dark", "Dark", "ダーク"),
    ("AsrModel_Automatic", "Automatic (best installed model for this PC)", "自動（この PC に合うインストール済みモデル）"),
    ("Model_Details", "{0} · {1} · {2}", "{0} · {1} · {2}"),
    ("ModelState_NotInstalled", "Not installed", "未インストール"),
    ("ModelState_Installed", "Installed", "インストール済み"),
    ("ModelState_Invalid", "Damaged — download again", "破損しています（再度ダウンロードしてください）"),
    ("Model_Downloading", "Downloading…", "ダウンロード中…"),
    ("Model_DownloadingPercent", "Downloading… {0}%", "ダウンロード中… {0}%"),
    ("Model_InstallFailed", "Download failed: {0}", "ダウンロードに失敗しました: {0}"),
    ("Model_Install.Content", "Download", "ダウンロード"),
    ("Model_Remove.Content", "Remove", "削除"),
    ("Model_Recommended.Text", "Recommended for this PC", "この PC に推奨"),
    ("ModelDialog_Title", "Download this model?", "このモデルをダウンロードしますか？"),
    ("ModelDialog_Content", "{0} ({1}) will be downloaded from {2}. License: {3}. It is verified before use, stored outside your Library, and can be removed at any time.", "{0}（{1}）を {2} からダウンロードします。ライセンス: {3}。使用前に検証し、ライブラリとは別に保存します。いつでも削除できます。"),
    ("ModelDialog_Primary", "Download", "ダウンロード"),
    ("RemoveModelDialog_Title", "Remove this model?", "このモデルを削除しますか？"),
    ("RemoveModelDialog_Content", "{0} will be deleted from this PC. Your recordings and transcripts are not affected.", "{0} をこの PC から削除します。録音や文字起こしには影響しません。"),
    ("RemoveModelDialog_Primary", "Remove", "削除"),
    ("Error_InvalidHotkey", "Use Ctrl, Alt or Win with a letter, digit or F-key (for example Ctrl+Alt+Shift+R).", "Ctrl・Alt・Win のいずれかと、英字・数字・F キーを組み合わせてください（例: Ctrl+Alt+Shift+R）。"),
    ("Settings_Version", "Version {0}", "バージョン {0}"),
    # --- Notifications ---
    ('SettingsTab_Recording.Text', 'Recording', '録音'),
    ('SettingsTab_Transcription.Text', 'Transcription & summary', '文字起こし・要約'),
    ('SettingsTab_Models.Text', 'Models', 'モデル'),
    ('SettingsTab_Data.Text', 'Data & backup', 'データとバックアップ'),
    ('SettingsTab_General.Text', 'General', '全般'),
    ('Settings_Advanced.Header', 'Advanced settings', '詳細設定'),
    ('Settings_Hotkey.Description', 'Works while you use any app. Leave it empty to turn it off.', 'どのアプリを使っているときでも押せます。空欄にすると無効になります。'),
    ('Settings_SystemAudio.Description', 'Besides the microphone, records what the PC plays (for example the other side of an online meeting).', 'マイクに加えて、PC で再生中の音（オンライン会議の相手の声など）も録音します。'),
    ('Settings_LiveTranscript.Description', 'A preview using a model installed on this PC. The final transcript is made after recording.', 'プレビュー用です。この PC のモデルを使います。正式な文字起こしは録音の後に作られます。'),
    ('Settings_PreventSleep.Description', 'Keeps long recordings from stopping when the PC would go to sleep.', '長い録音の途中で PC がスリープしないようにします。'),
    ('Settings_KeepRecording.Description', 'Closing the window while recording keeps recording in the notification area.', '録音中にウィンドウを閉じると、通知領域（タスクトレイ）で録音を続けます。'),
    ('Settings_Retention.Description', 'Converting after processing saves disk space.', '処理の後に圧縮すると、容量を節約できます。'),
    ('Settings_Language.Description', 'Choose one if automatic detection gets it wrong.', '自動判定がうまくいかないときに指定します。'),
    ('Settings_AutoProcess.Description', "When off, start transcription from the recording's page.", 'オフにすると、録音の画面から手動で始めます。'),
    ('Settings_AsrModel.Description', 'Automatic is fine in most cases.', '通常は「自動」のままで構いません。'),
    ('Settings_SummaryEngine.Description', 'On a PC with 8 GB of memory, "Extraction only" is recommended.', 'メモリが 8 GB の PC では「抜き出しのみ」がおすすめです。'),
    ('Settings_Mode.Description', 'Whether heavy work runs on battery power.', 'バッテリー駆動中に重い処理をするかどうかを選びます。'),
    ('Settings_YtDlpCustom.Text', 'Use a yt-dlp.exe you downloaded yourself', 'ご自身で入手した yt-dlp.exe を使う'),
    ('Settings_LibraryFolder.Header', 'Library folder', 'ライブラリのフォルダ'),
    ('Settings_LibraryUsage.Header', 'Space used by the Library', 'ライブラリの使用容量'),
    ('Settings_UsageDetails.Header', 'Space used by Kakitome', 'Kakitome の使用容量の内訳'),
    ('Settings_AutomaticBackup.Description', 'Keeps the latest 3 backups.', '最新の 3 件を残します。'),
    ('Settings_BackupFolder', 'Backup folder: {0}', 'バックアップの保存先: {0}'),
    ('Settings_Troubleshoot.Header', 'Troubleshooting and uninstall', 'トラブルシューティングとアンインストール'),
    ('Maintenance_ClearCacheCard.Header', 'Clear cache', 'キャッシュを消去'),
    ('Maintenance_ResetConfigCard.Header', 'Reset settings', '設定をリセット'),
    ('Maintenance_FactoryResetCard.Header', 'Factory reset', '初期状態に戻す'),
    ('Maintenance_UninstallCard.Header', 'Uninstall Kakitome', 'Kakitome をアンインストール'),
    ('Settings_UiLanguage.Description', 'Takes effect after Kakitome restarts.', 'Kakitome の再起動後に反映されます。'),
    ('Settings_NotificationsSection.Text', 'Notifications', '通知'),
    ('Settings_Notifications.Description', 'Shows a Windows notification while Kakitome is in the background.', 'Kakitome がバックグラウンドのときに、Windows の通知でお知らせします。'),
    ('Queue_SectionActive.Text', 'In progress or needs attention', '処理中・要確認'),
    ('Queue_SectionFinished.Text', 'Finished (last 7 days)', '完了した処理（直近 7 日間）'),
    ('Queue_GroupRunning', 'Processing ({0} of {1} steps done)', '処理中（{1} 工程中 {0} 工程完了）'),
    ('Queue_GroupWaiting', 'Waiting ({0} of {1} steps done)', '待機中（{1} 工程中 {0} 工程完了）'),
    ('Queue_GroupPaused', 'Paused', '一時停止中'),
    ('Queue_GroupDone', 'Done ({0} steps)', '完了（{0} 工程）'),
    ('Queue_GroupFailed', 'A step failed — retry it below', '失敗した工程があります。下の［再試行］でやり直せます'),
    ('Settings_AutoDownload.Header', 'Download what is missing automatically', '足りないモデルとツールを自動でダウンロードする'),
    ('Settings_AutoDownload.Description', 'At startup, downloads what is missing: the speech recognition model recommended for this PC, the recommended summary AI (PCs with 16 GB of memory or more) and yt-dlp for URL import. Not on a metered connection.', '起動時に、足りないものを自動でダウンロードします：この PC に推奨の音声認識モデル、推奨の要約用 AI（メモリ 16 GB 以上の PC のみ）、URL 取り込み用の yt-dlp。従量制の接続では行いません。'),
    ('Settings_AsrModels.Text', 'Speech recognition', '音声認識'),
    ('Settings_AsrModelsHint.Text', 'Turns recordings into text. One model is enough; with several, Kakitome picks the best one for this PC.', '録音を文字にするモデルです。1 つあれば文字起こしできます。複数あるときは、この PC に合うものを自動で使います。'),
    ('Settings_SummaryModels.Text', 'Summary AI (optional)', '要約用 AI（任意）'),
    ('Settings_SummaryModelsHint.Text', 'Writes the summary text. Without one, the summary is made by picking out the key sentences of the transcript.', '要約の文章を作るモデルです。ないときは、文字起こしから重要な文を抜き出して要約します。'),
    ('Settings_Tools.Text', 'Tools', 'ツール'),
    ('Settings_ToolsHint.Text', 'Programs Kakitome uses for some features.', '一部の機能で使うプログラムです。'),
    ('ModelNote_whisper-large-v3-turbo-q5_0', 'Most accurate. For PCs with a GPU (fast on the GPU, slow on the CPU alone).', '最も高精度。GPU のある PC におすすめです（GPU で高速に動きます。CPU だけでは遅くなります）。'),
    ('ModelNote_whisper-small-q5_1', 'For PCs without a GPU. Light and fast on the CPU, fairly robust to noise.', 'GPU のない PC（CPU のみ）におすすめです。軽くて速く、雑音にも比較的強いモデルです。'),
    ('ModelNote_reazonspeech-k2-v2-int8', 'Japanese only and very light (CPU). Good in quiet places; weak with noise.', '日本語専用で、とても軽いモデルです（CPU）。静かな場所での録音向けで、雑音には弱めです。'),
    ('ModelNote_qwen3-4b-instruct-2507-q4_k_m', 'Most accurate summaries. For PCs with 16 GB of memory or more; faster with a GPU.', '要約の精度が最も高いモデルです。メモリ 16 GB 以上の PC 向けで、GPU があると速くなります。'),
    ('ModelNote_phi-4-mini-instruct-q4_k_m', 'An alternative summary model, less accurate than Qwen3. For PCs with 16 GB of memory or more.', 'Qwen3 の代わりに使える要約モデルです（精度は Qwen3 より低め）。メモリ 16 GB 以上の PC 向けです。'),
    ('Stage_diarize', 'Speaker identification', '話者の識別'),
    ('JobError_NoAsrModel', 'No speech recognition model is installed yet. This is retried automatically when the model is ready (Settings › Models).', '音声認識モデルがまだありません。モデルの準備ができると自動でやり直します（設定 › モデル）。'),
    ('JobError_EditedOutside', '{0} was edited outside Kakitome, so it was not overwritten.', '{0} が Kakitome の外で編集されていたため、上書きしませんでした。'),
    ('JobError_AudioUnreadable', 'The audio could not be read: {0}', '音声を読み込めませんでした：{0}'),
    ('JobError_NoTranscript', 'There is no transcript yet.', '文字起こしがまだありません。'),
    ('JobError_SourceMissing', 'The original file is no longer there.', '元のファイルが見つかりません。'),
    ('JobError_BadUrl', 'The URL is not valid.', 'URL が正しくありません。'),
    ('JobError_NoYtDlp', 'URL import needs yt-dlp. Install it in Settings › Models.', 'URL からの取り込みには yt-dlp が必要です。設定 › モデルでインストールしてください。'),
    ('JobError_UnsupportedMedia', 'The downloaded file ({0}) is not a supported format.', 'ダウンロードしたファイル（{0}）は対応していない形式です。'),
    ('JobError_YtDlpFailed', 'yt-dlp could not download the media.', 'yt-dlp で動画・音声を取得できませんでした。'),
    ('JobError_DownloadFailed', 'Download of {0} failed: {1}', '{0} のダウンロードに失敗しました：{1}'),
    ('JobError_NoEncoder', 'No audio encoder is available on this PC.', 'この PC には音声の変換に必要な機能がありません。'),
    ('JobError_RetentionCheck', 'The converted audio did not match the recording, so the original was kept.', '変換後の音声が録音と一致しなかったため、元の音声を残しました。'),
    ('JobError_BackupWrite', 'The backup could not be written: {0}', 'バックアップを書き込めませんでした：{0}'),
    ('JobError_BackupMissing', 'The backup file is no longer there.', 'バックアップのファイルが見つかりません。'),
    ('JobError_NoSummary', 'No summary engine is available.', '要約に使える機能がありません。'),
    ('JobError_UnknownKind', 'This version of Kakitome cannot run this step ({0}).', 'このバージョンの Kakitome では、この処理（{0}）を実行できません。'),
    ('Settings_CheckForUpdates.Header', 'Check for updates', 'アップデートを確認する'),
    ('Settings_CheckForUpdates.Description', 'Once a day, asks GitHub whether a newer version is out and tells you. Nothing is downloaded or sent besides the request.', '1 日 1 回、新しいバージョンが公開されていないか GitHub に問い合わせてお知らせします。問い合わせのほかに、ダウンロードや送信はしません。'),
    ('Settings_CheckUpdatesNow.Content', 'Check now', '今すぐ確認'),
    ('Update_Checking', 'Checking…', '確認しています…'),
    ('Update_Available', 'Kakitome {0} is available (you have {1}).', 'Kakitome {0} が公開されています（使用中: {1}）。'),
    ('Update_UpToDate', 'You have the latest version ({0}).', '最新のバージョンです（{0}）。'),
    ('Update_Failed', 'Could not check for updates. Check the internet connection.', 'アップデートを確認できませんでした。インターネット接続を確認してください。'),
    ('Home_Update.Title', 'New version', '新しいバージョン'),
    ('Update_Open.Content', 'Download page', 'ダウンロードページ'),
    ('Notify_Update', 'A new version of Kakitome is available', 'Kakitome の新しいバージョンがあります'),
    ('Diagnostics_Card.Header', 'Report a problem', '不具合の報告'),
    ('Diagnostics_Card.Description', 'Saves one zip with the logs, this PC, settings and the processing history to attach to a GitHub issue. No audio, transcripts, summaries or titles; your user and folder names are hidden. Project and file names can appear in logs.', 'GitHub の Issue に添付する zip を保存します（ログ・PC の情報・設定・処理の履歴）。録音・文字起こし・要約・タイトルは含まず、ユーザー名やフォルダー名は伏せます。ログにはプロジェクト名やファイル名が含まれることがあります。'),
    ('Diagnostics_Export.Content', 'Save diagnostics…', '診断情報を保存…'),
    ('Diagnostics_OpenLogs.Content', 'Open log folder', 'ログフォルダーを開く'),
    ('Diagnostics_Saved', 'Diagnostics saved. Attach the zip to the issue.', '診断情報を保存しました。zip を Issue に添付してください。'),
    ('Diagnostics_Failed', 'Diagnostics could not be saved: {0}', '診断情報を保存できませんでした：{0}'),
    ('Home_ProcessingWaiting', '{0} waiting — {1}', '{0} 件の処理が待機中：{1}'),
]

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" msdata:Ordinal="1" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""

root = os.path.join(os.path.dirname(__file__), "..", "src", "Kakitome.App", "Strings")
keys = [k for k, _, _ in STRINGS]
assert len(keys) == len(set(keys)), "duplicate keys"
for index, culture in ((1, "en-US"), (2, "ja-JP")):
    lines = [HEADER]
    for row in STRINGS:
        lines.append(f'  <data name="{escape(row[0])}" xml:space="preserve"><value>{escape(row[index])}</value></data>\n')
    lines.append("</root>\n")
    path = os.path.join(root, culture, "Resources.resw")
    with open(path, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("".join(lines))
print(f"wrote {len(STRINGS)} strings x 2 cultures")
