// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Kakitome.Storage.Persistence;

#nullable disable

namespace Kakitome.Storage.Persistence.Migrations
{
    [DbContext(typeof(KakitomeDbContext))]
    [Migration("20260930145848_InitialLibraryIndex")]
    partial class InitialLibraryIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Kakitome.Storage.Persistence.ArtifactRow", b =>
                {
                    b.Property<string>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastWriteUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.HasKey("RecordingId", "FileName");

                    b.ToTable("Artifacts", (string)null);
                });

            modelBuilder.Entity("Kakitome.Storage.Persistence.LibraryIssueRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LibraryIssues", (string)null);
                });

            modelBuilder.Entity("Kakitome.Storage.Persistence.RecordingRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CaptureStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAudio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasExternalChanges")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSummary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTranscript")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RecordedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtcTicks");

                    b.HasIndex("Folder")
                        .IsUnique();

                    b.HasIndex("Project");

                    b.ToTable("Recordings", (string)null);
                });

            modelBuilder.Entity("Kakitome.Storage.Persistence.RecordingTagRow", b =>
                {
                    b.Property<string>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordingId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("RecordingTags", (string)null);
                });

            modelBuilder.Entity("Kakitome.Storage.Persistence.RecordingTagRow", b =>
                {
                    b.HasOne("Kakitome.Storage.Persistence.RecordingRow", null)
                        .WithMany("Tags")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kakitome.Storage.Persistence.RecordingRow", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
